export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

// Customers
export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const LOAD_CUSTOMERS_FAIL = 'LOAD_CUSTOMERS_FAIL';
